#!/bin/sh

if [ $# -lt 3 ] ; then
echo -e "Wrong number of parameters."
echo -e "Usage:"
echo -e " renall 'filepat' findstring replacestring\n"
exit 1
fi

#echo $1 $2 $3
for i in `find . -name "$1" -exec grep -l "$2" {} \;`
do
mv "$i" "$i.sedsave"
sed "s/$2/$3/g" "$i.sedsave" > "$i"
echo $i
#rm "$i.sedsave"
done 
